### ISSUE TITLE
Wheel of latest version on Pypi is invalid

### ISSUE THREAD

**Issue by fhoering** [jupyter/testpath#19]
The wheelfile of the version that has just been uploaded on Pypi is invalid:
https://pypi.org/project/testpath/0.4.3/

```
$wheel version
wheel 0.33.6
$ python
>>> from wheel.wheelfile import WheelFile
>>> wf = WheelFile("testpath-0.4.3-py2.py3-none-any.whl")
>>> wf.extractall("/tmp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/zipfile.py", line 1524, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib64/python3.6/zipfile.py", line 1577, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/home/f.horing/private/tf_bidding_env/lib64/python3.6/site-packages/wheel/wheelfile.py", line 98, in open
    raise WheelError("No hash found for file '{}'".format(native(ef_name)))
wheel.cli.WheelError: No hash found for file 'testpath-0.4.3.dist-info/tmp/tmpsad01phf/testpath-0.4.3/LICENSE'
```

**Comment by takluyver** [comment]
That was me using my in-development version of the packaging tool that builds the wheel. I'll investigate soon and release a new wheel once I've figured it out.

**Comment by takluyver** [comment]
Thanks for the quick feedback.

**Comment by takluyver** [comment]
OK, 0.4.4 is out now, and hopefully is valid.

**Comment by takluyver** [comment]
If you're curious, here's the change that was needed: https://github.com/takluyver/flit/commit/e9d4cea42991ba9344e6abef8ef6813c0f1b8cd3

**Comment by fhoering** [comment]
Thanks
